[package]
name = "sqsproxyd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "a"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
dotenv = "0.15"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
url = { version = "2.2", features = ["serde"] }
