version: '3.8'
services:
  sqsproxyd:
    image: sqsproxyd
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: sqsproxyd
    depends_on:
      - sqsproxyd-api
      - sqsproxyd-sqs
  release-build:
    image: sqsproxyd:release-builder
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: release-builder
    volumes:
      - .:/usr/src/sqsproxyd
  dev:
    image: sqsproxyd:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - .:/usr/src/sqsproxyd
    depends_on:
      - sqsproxyd-api
      - sqsproxyd-sqs
  sqsproxyd-api:
    image: ealen/echo-server:latest
    ports:
      - "4000:80"
  sqsproxyd-sqs:
    image: roribio16/alpine-sqs:latest
    ports:
      - "9324:9324"
    volumes:
      - ./docker/sqs:/opt/custom
