version: '3.8'
services:
  builder:
    image: sqsproxyd:builder
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder
  release-builder:
    image: sqsproxyd:release-builder
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: release-builder
  dev:
    image: sqsproxyd:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - .:/usr/src/sqsproxyd
    command: bash
    tty: true
    depends_on:
      - api
  api:
    image: ealen/echo-server:latest
    ports:
      - 4000:80
