[env]
VERSION = { script = ["cargo metadata --no-deps | jq -r '.packages[0].version'"] }
IMAGE_REPOSITORY = { source = "${DOCKER_REPOSITORY}", default_value = "ohke/sqsproxyd" }

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.check]
dependencies = [
    "format",
    "clippy",
    "test"
]

[tasks.build-image]
script = '''
#!/bin/bash -eu

docker build -f ./docker/Dockerfile --target sqsproxyd -t ${IMAGE_REPOSITORY}:${VERSION} .
'''

[tasks.push-repository]
dependencies = [
    "build-image"
]
script = '''
#!/bin/bash -eu

docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_TOKEN} https://index.docker.io/v1/
docker push ${IMAGE_REPOSITORY}:${VERSION}
'''
