on: push
name: CI
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: Swatinem/rust-cache@v1
      - run: cargo make check
