on:
  push:
    paths:
      - docker/Dockerfile
name: Lint Dockerfile
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: docker/Dockerfile
          failure-threshold: warning
